version: '3'

services:
  server:
    build: .
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
    environment:
      - DEBUG=true
    ports:
      - 3000:3000
    command: sh -c "yarn && yarn server:dev"
  front:
    build: .
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
    environment:
      - DEBUG=true
    ports:
      - 8080:8080
    command: sh -c "yarn && yarn front:dev"

volumes:
  app_node_modules: