version: '3'

services:
  app:
    build: .
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
    environment:
      - DEBUG=true
    ports:
      - 3000:3000
    command: yarn server:dev
  front:
    build: .
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
    environment:
      - DEBUG=true
    ports:
      - 8080:8080
    command: yarn front:dev

volumes:
  app_node_modules: